"""Add provinces, municipalities, and subdivisions models

Revision ID: 5987716e1130
Revises: 9184d4cf3729
Create Date: 2025-07-01 04:57:43.497990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5987716e1130'
down_revision: Union[str, Sequence[str], None] = '9184d4cf3729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subdivisions', 'subdivision_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               autoincrement=True)
    op.alter_column('subdivisions', 'subdivision_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('subdivisions', 'zoning_color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subdivisions', 'zoning_color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subdivisions', 'subdivision_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('subdivisions', 'subdivision_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
