"""Add remaining core tables

Revision ID: be3ab240b473
Revises: 5987716e1130
Create Date: 2025-07-01 04:58:38.101795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be3ab240b473'
down_revision: Union[str, Sequence[str], None] = '5987716e1130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('parcels_base', 'parcel_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # op.add_column('streets', sa.Column('street_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('streets', 'street_id')
    op.alter_column('parcels_base', 'parcel_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
