"""add tile_urls table for tile discovery and pipeline integration

Revision ID: ecb5e54cbea4
Revises: e1e813183ae0
Create Date: 2025-07-08 16:27:50.367928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb5e54cbea4'
down_revision: Union[str, Sequence[str], None] = 'e1e813183ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tile_urls',
        sa.Column('id', sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column('url', sa.Text(), nullable=False, unique=True),
        sa.Column('zoom_level', sa.Integer(), nullable=False),
        sa.Column('x', sa.Integer(), nullable=False),
        sa.Column('y', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=32), nullable=False, server_default='pending'),
        sa.Column('last_checked_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.create_index('idx_tile_urls_status', 'tile_urls', ['status'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tile_urls_status', table_name='tile_urls')
    op.drop_table('tile_urls')
    # ### end Alembic commands ###
